small changes
CrucibleMC/Grimoire pull request #10
Opened 2021-07-03 15:46 UTC by zeff9801

2021-07-03 17:13 UTC, evernife approved these changes
Seems ok

2021-07-03 20:31 UTC, Aizistral requested changes
No way I'll let this be merged as-is.

2021-07-03 20:31 UTC, Aizistral commented on Grimoire-mc1.12.2/src/main/java/io/github/crucible/grimoire/mc1_12_2/api/integration/eventhelper/IEventHelperIntegration.java
> +    boolean canBreak(@Nonnull EntityPlayer player, @Nonnull BlockPos pos);
Could you please not strip away `public` modifier from interface/annotation methods? I know they aren't necessary, but I prefer them being in place for aesthetical reasons.

2021-07-03 20:31 UTC, Aizistral commented on Grimoire-shared/src/main/java/io/github/crucible/omniconfig/api/properties/IAbstractProperty.java
> -public abstract interface IAbstractProperty {
Also this. I know all interfaces are inherently abstract, but I mark them as such for the purpose of indication that nothing implements this interface on its own, only interfaces that extend this one.

2021-07-03 20:31 UTC, Aizistral commented on Grimoire-shared/src/main/java/io/github/crucible/omniconfig/api/core/VersioningPolicy.java
> -    DISMISSIVE;
Plase leave these. Though not neccessary for enums without constructor, there might be constructor someday.

2021-07-03 20:31 UTC, Aizistral commented on Grimoire-shared/src/main/java/io/github/crucible/omniconfig/api/builders/BuildingPhase.java
> -    private BuildingPhase() {
Same as for interface methods modifier.

2021-07-03 20:31 UTC, Aizistral commented on Grimoire-shared/src/main/java/io/github/crucible/grimoire/common/core/MixinConfiguration.java
> +        return this.isLoaded || !this.isRuntimeGenerated() || ConfigBuildingManager.areRuntimeConfigsGenerated();
How the hell this is supposed to work well?

2021-07-03 20:31 UTC, Aizistral commented on Grimoire-shared/src/main/java/io/github/crucible/grimoire/common/api/integration/IModIntegrationRegistry.java
> +    @Nullable <T extends IModIntegration> T getIntegration(Class<T> integrationClass);
No, you don't put annotation and its target methods in the same line. Please, for the love of gods.

2021-07-03 20:31 UTC, Aizistral commented on Grimoire-shared/src/main/java/io/github/crucible/grimoire/common/api/eventbus/CoreEvent.java
> -    public static enum Result {
Why?

2021-07-03 21:11 UTC, evernife commented
If he revert all that, it will be reverting like more than 70% of his changes.

What he did was just follow standarts.

![image](https://user-images.githubusercontent.com/11357801/124366961-fb21d380-dc29-11eb-9d82-acbc30e83070.png)

_(Maybe this changes were automatic)_

2021-07-03 21:24 UTC, Aizistral commented
> _(Maybe this changes were automatic)_

Most probably. Redundant modifiers are not "specifying them is an error" modifiers, they are "you don't have to specify them, but if you wanna - go nuts" modifiers.  I find the code easier to perceive and navigate when they are in place. which is by no measure less important than just having that code doing its functional job.

2021-07-04 05:50 UTC, Aizistral commented
I mean, you don't have to care as much if you only touch upon internals, or introduce some new feature to the API. In latter case I can always make corrections myself if something purely visual annoys me. But if you're gonna auto-refractor everything you didn't write yourself, you could at least bother enough to ask which of your intended changes would be welcome first.

2021-07-04 21:07 UTC, evernife commented
> I mean, you don't have to care as much if you only touch upon internals, or introduce some new feature to the API. In latter case I can always make corrections myself if something purely visual annoys me. But if you're gonna auto-refractor everything you didn't write yourself, you could at least bother enough to ask which of your intended changes would be welcome first.

I know exactly how you feel :D

2021-08-24 09:01 UTC, Aizistral commented
Since it's been over a month and no response followed from author of the PR, I am closing this.

2021-08-24 09:01 UTC, closed without merging